-- CreateTable
CREATE TABLE "Settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "buttonLabel" TEXT,
    "preorderMessage" TEXT,
    "messagePosition" TEXT,
    "badgeEnabled" BOOLEAN NOT NULL DEFAULT true,
    "badgeText" TEXT,
    "badgeShape" TEXT,
    "inventoryManagement" BOOLEAN NOT NULL DEFAULT false,
    "orderTag" TEXT,
    "syncInventory" BOOLEAN NOT NULL DEFAULT false,
    "hideBuyNow" BOOLEAN NOT NULL DEFAULT false,
    "badgesOnCollection" BOOLEAN NOT NULL DEFAULT false,
    "badgeOnProduct" BOOLEAN NOT NULL DEFAULT false,
    "buttonsOnCollection" BOOLEAN NOT NULL DEFAULT false,
    "quickviewSupport" BOOLEAN NOT NULL DEFAULT false,
    "cartLabelText" TEXT,
    "cartLabelKey" TEXT,
    "showAdditionalButtons" BOOLEAN NOT NULL DEFAULT false,
    "preventOrdering" BOOLEAN NOT NULL DEFAULT false,
    "insufficientStockMsg" TEXT,
    "notifyCustomers" BOOLEAN NOT NULL DEFAULT false,
    "partOrderMsg" TEXT,
    "mixedCartWarning" BOOLEAN NOT NULL DEFAULT false,
    "discountType" TEXT,
    "startDate" TEXT,
    "startTime" TEXT,
    "endDate" TEXT,
    "endTime" TEXT,
    "shopTimezone" TEXT,
    "selectedTheme" TEXT,
    "selectors" TEXT,
    "monthlyChargeLimit" TEXT,
    "bccMe" BOOLEAN NOT NULL DEFAULT false,
    "bccEmail" TEXT,
    "emailSubject" TEXT,
    "emailHeader" TEXT,
    "emailLineItem" TEXT,
    "emailLineFooter" TEXT,
    "senderEmail" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "Settings_shop_key" ON "Settings"("shop");
